# Use postgres/example user/password credentials
version: '3.1'

services:

  db_postgres:
    image: postgres:latest
    # restart: always 
    container_name: postgres_container
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tri29112001
      POSTGRES_DB: demo
