name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for api
      run: docker build ./Mail/Imail/BE --file Dockerfile --tag api:$(date +%s)
    - uses: actions/checkout@v2
    - name: Build the Docker image for react
      run: docker build ./Mail/Imail/FE --file Dockerfile --tag template:$(date +%s)
